spring:
 application:
  name: delivery-control-api
 datasource:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/delivery}
  username: ${DATABASE_USER:delivery}
  password: ${DATABASE_PASSWORD:delivery}
 jpa:
  hibernate:
   ddl-auto: validate
  open-in-view: false
 flyway:
  enabled: true
management:
 endpoints:
  web:
   exposure:
    include: health,info,metrics,prometheus
server:
 port: ${PORT:8080}

